config/routes.rb
Chinese::Application.routes.draw do

  ActiveAdmin.routes(self)
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  post "study" => "words#study", :as => "study"
  post "show_answer" => "words#show_answer", :as => "show_answer"
  post "knew" => "words#knew", :as => "knew"
  post "missed" => "words#missed", :as => "missed"
  root :to => "welcome#show"
  resources :users
  resources :sessions
  

end

app/models/user.rb
class User < ActiveRecord::Base
  
  attr_accessor :password
  before_save :encrypt_password

  has_deck :words
  has_many :words
  
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email
  
  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
end

app/models/word.rb
class Word < ActiveRecord::Base

  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.authenticate(params[:email], params[:password])
    if user
      session[:user_id] = user.id
      clear_del_words(user)
      add_new_words(user)
      redirect_to root_url, :notice => "Logged in!"
    else
      flash.now.alert = "Invalid email or password"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Logged out!"
  end

  # Add new words in the DB to the user study deck
  def add_new_words(user)
    Word.where(user_id: user.id).each do |w| 
      if !user.words.include?(w)
        user.words << w
      end
    end
  end

  # Clear deleted words in the DB from the user study deck
  def clear_del_words(user)
    ids = user.words.items.pluck("id")
    ids.each do |i|
      if Word.where(user_id: user.id).where(id: i).blank?
        puts "deleting " + i.to_s 
        user.words.items.find(i).delete
      end
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_url, :notice => "Signed up!"
    else
      render "new"
    end
  end


  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController


end

app/controllers/words_controller.rb
class WordsController < ApplicationController

  def new
    @word = Word.new
  end

  def create
    @word = Word.create(word_params)
  end

  def study
    @word = current_user.words.next
  end

  def show_answer
    @word = Word.find(params[:word])
    @word.attributes.each do |k,v| 
      v.nil? ? @word.update_attribute(k, "") : 0
    end
  end

  def knew
    current_user.right_answer_for!(Word.find(params[:word]))
    @word = current_user.words.next
    if @word.nil? 
      redirect_to root_path
    else
      render 'study'
    end
  end

  def missed
    current_user.wrong_answer_for!(Word.find(params[:word]))
    @word = current_user.words.next
    if @word.nil? 
      redirect_to root_path
    else
      render 'study'
    end
  end

private

  def word_params
    params.require(:word).permit!
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/word_helper.rb
module WordHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Chinese</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <div class="row">
    <div class="user-nav">
      <% if current_user %>
        <%= link_to "Log out", log_out_path %>
      <% else %>
        <%= link_to "Sign up", sign_up_path %> or
        <%= link_to "log in", log_in_path %>
      <% end %>
    </div>
  </div>

  <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, :id => "flash_#{name}" %>
  <% end %>
</div>

  <%= yield %>

</body>
</html>

app/views/users/new.html.erb
<div class="login-fields">

    <h1>Sign Up</h1>
      <%= form_for @user do |f| %>
      <% if @user.errors.any? %>
	<div class="error_messages">
	  <h2>Form is invalid</h2>
	  <ul>
	    <% for message in @user.errors.full_messages %>
	      <li><%= message %></li>
	    <% end %>
	</ul>
      </div>
    <% end %>
    <p>
      <%= f.label :email %><br />
      <%= f.text_field :email %>
    </p>
    <p>
      <%= f.label :password %><br />
      <%= f.password_field :password %>
    </p>
    <p>
      <%= f.label :password_confirmation %><br />
      <%= f.password_field :password_confirmation %>
    </p>
    <p><%= button_tag "Sign up", :class => "btn-primary-xl" %></p>
  <% end %>
</div>

app/views/welcome/show.html.erb
<div class="container">
  <div class="row">
    <div class="content">

      <h1> Welcome to flashcards!</h1>

      <% if current_user %>
        <p>Cards due: <%= current_user.words.review.count %></p>
        <% if current_user.words.next == nil %>
          <p>No words to study</p>
        <% else %>  
          <%= link_to "Study", {:controller => "words", :action => "study"}, :class => "btn-primary-xl", :style => "text-decoration: none; color: #FFF", method: :post %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/words/show_answer.html.erb
<div class="container">
  <div class="row">
    <div class="content">
      <h1><%= @word.native.html_safe %></h1>
      <h3><%= @word.translit.html_safe %></h3>
      <h3><%= @word.translat.html_safe %></h3>
      <h3 style="color: grey"><%= @word.sentence.html_safe %></h3>
      <h3 style="color: grey"><%= @word.sent_trans.html_safe %></h3>
      <h1></h1>
      <div class="col-sm-6">
        <%= link_to "Knew it", {:controller => "words", :action => "knew", :word => @word}, :class => "btn-success-xl", :style => "text-decoration: none; color: #FFF", method: :post %>
      </div>
      <div class="col-sm-6">
        <%= link_to "Missed it", {:controller => "words", :action => "missed", :word => @word}, :class => "btn-danger-xl", :style => "text-decoration: none; color: #FFF", method: :post  %>
      </div>
    </div>
  </div>
</div>

app/views/words/study.html.erb
<div class="container">
  <div class="row">
    <div class="content">
      <h1><%= @word.native %></h1>
      <%= link_to "Show answer", {:controller => "words", :action =>"show_answer", :word => @word}, :class => "btn-primary-xl", :style => "text-decoration: none; color: #FFF", method: :post %>
    </div>
  </div>
</div>